print("-------Python Operators-------")
print("1.Arithmetic operators \n""2.Assignment operator\n""3.Comparison operator\n""4.Logical operator\n""5.Identity operator\n""6.Membership operator\n""7.Bitwise operator\n")
print("\n")
print("---Arithmetic operator---")
print("1.Addition\n""2.Subtraction\n""3.Multiplication\n""4.Division\n""5.Modulus\n""6.Exponent\n""7.Floor division")
print("\n")
print("----Assignment operator----")
print("^ is the xor operator ")
print(">>= right bitwise operator")
print(">>= left bitwise operator")
print("\n")
print("----Identity operator----")
print("in operator")
x = ["apple", "banana"]
print("banana" in x)
print("\n")
print("not in operator")
x = ["apple", "banana"]
print("pineapple" not in x)